create/urls.py
from django.urls import path
from . import views

app_name = 'create'

urlpatterns = [
    path('', views.create, name='create'),
]

homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
]

scheduleform/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('create/', include('create.urls')),
    path('see/', include('see.urls')),
]

see/urls.py
from django.urls import path
from . import views

app_name = 'see'

urlpatterns = [
    path('', views.see, name='see'),
    path('delete/<id>', views.delete, name='delete'),
    path('delete-all', views.delete_all, name='delete_all')
]

create/models.py
from django.db import models

# Create your models here.
class Entry(models.Model):
    CATEGORIES = [
        ('Quiz', 'Quiz'),
        ('Exam', 'Exam'),
        ('Meeting', 'Meeting'),
        ('Other', 'Other'),
    ]
    name = models.CharField(max_length=30)
    date = models.DateField()
    time = models.TimeField()
    place = models.CharField(max_length=20)
    category = models.CharField(max_length=7, choices=CATEGORIES)

    def create(self):
        self.save()

    def __str__(self):
        return self.name

homepage/models.py
from django.db import models

# Create your models here.

see/models.py
from django.db import models

# Create your models here.

create/forms.py
from django import forms
from .models import Entry
from django.forms import TextInput

class CreateEntry(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ('name', 'date', 'time', 'place', 'category',)
    def __init__(self, *args, **kwargs):
        super(CreateEntry, self).__init__(*args, **kwargs)
        self.fields['date'].widget = TextInput(attrs={
            'type': 'date',
            'class': 'dateinput',})
        self.fields['time'].widget = TextInput(attrs={
            'type': 'time',})

create/views.py
from django.shortcuts import render, redirect
from .forms import CreateEntry
from .models import Entry

# Create your views here.

# def create(request):
#     # entries = Entry.objects.all()
#     if request.method == "POST":
#         form = CreateEntry(request.POST)
#         if form.is_valid():
#             post = form.save(commit=False)
#             post.save()
#             return redirect('create:see')
#     else:
#         form = CreateEntry()
#     map = {
#         'form': form,
#     }
#     return render(request, 'create.html', map)



def create(request):
    form = CreateEntry(request.POST or None)
    # entries = Entry.objects.all().values()
    if (request.method == 'POST' and form.is_valid()):
        sched = {
            'name': request.POST['name'],
            'date': request.POST['date'],
            'time': request.POST['time'],
            'place': request.POST['place'],
            'category': request.POST['category'],
            # 'data': entries,
            'form': CreateEntry(),
        }

        new_entry = Entry(name=sched['name'], date=sched['date'], time=sched['time'], place=sched['place'], category=sched['category'])
        new_entry.save()
        return render(request, 'create.html', sched)
    else:
        map = {
            'form': CreateEntry(),
        }
        return render(request, 'create.html', map)

homepage/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'index.html')

see/views.py
from django.shortcuts import render, redirect
from create.models import Entry
# Create your views here.

def see(request):
    entries = Entry.objects.all()
    map = {
        'data': entries,
    }
    return render(request, 'schedule.html', map)

def delete(request, id):
   ent = Entry.objects.get(id = id)
   ent.delete()
   return render(request, 'schedule.html')

def delete_all(request):
    Entry.objects.all().delete()
    return redirect('see:see')

create/templates/create.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>schedule</title>
</head>
<body class="create">
    <div class="theform">
        <form method="POST">
            {% csrf_token %}
            {{ form }}
            <button type="submit">submit</button>
            <a href="{% url 'see:see' %}" class="sched">See Schedule</a>
        </form>
    </div>
</body>
</html>

homepage/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>schedule</title>
</head>
<body class="index">
    <img src="{% static 'images/redtriangle.png' %}" alt="segitiga" class="asset1">
    <div class="container">
        <button type="button" onclick="window.location.href='{% url 'create:create' %}'">create an entry</button>
        <br>
        <button type="button" onclick="window.location.href='{% url 'see:see' %}'">see schedule</button>
    </div>
    <img src="{% static 'images/pinkcircle.png' %}" alt="lingkaran" class="asset2">
</body>
</html>

see/templates/schedule.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>schedule</title>
</head>
<body class="see">
    {% if not data %}
    <h2>Schedule is empty!</h2>
    <button type="button" onclick="window.location.href='{% url 'create:create' %}'" class="addbutton">Add New Entry</button>
    {% else %}
    
    <h2>the schedule</h2>
    {% for entry in data %}
    <div class="agenda">
        <h3>{{entry.name}}</h3>
        <p> {{entry.date}} • {{entry.time}} • {{entry.place}} • {{entry.category}} </p>
        <a href="{% url 'see:delete' id=entry.id %}">Delete Entry</a>
    </div>
    {% endfor %}

    <button type="button" onclick="window.location.href='{% url 'create:create' %}'" class="addbutton">Add New Entry</button>
    <a href="{% url 'see:delete_all' %}">Delete All Entries</a>
    {% endif %}
</body>
</html>